const phones = {
  category: "Smartphones",
  products: [
    {
      id: 1,
      name: "Premium Plus Ultra",
      brand: "Nexus",
      model: "XP7",
      price: 1099.99,
      currency: "USD",
      colors: ["Midnight Black", "Glacier Silver", "Sage Green"],
      storage: "256 GB",
      image_url: "mini-tech/images/placholder.jpg",
      description:
        "Flagship phone with a pro-grade camera system, super bright display, and all-day battery life.",
    },
    {
      id: 2,
      name: "Galaxy Apex",
      brand: "Samsung",
      model: "Galaxy A55",
      price: 499.99,
      currency: "USD",
      colors: ["Awesome Graphite", "Awesome Lilac", "Awesome Blue"],
      storage: "128 GB",
      image_url: "./mini-tech/images/placholder.jpg",
      description:
        "A powerful and versatile phone with a stunning AMOLED display and long-lasting battery.",
    },
    {
      id: 3,
      name: "iPhone",
      brand: "Apple",
      model: "iPhone 15",
      price: 829.0,
      currency: "USD",
      colors: ["Black", "Blue", "Green", "Pink", "Yellow"],
      storage: "128 GB",
      image_url: "/images/placholder.jpg",
      description:
        "The powerful iPhone 15 features a durable color-infused glass design, a powerful camera system, and the A16 Bionic chip.",
    },
    {
      id: 4,
      name: "PowerPhone Pro",
      brand: "Motorola",
      model: "Edge 40 Neo",
      price: 399.99,
      currency: "USD",
      colors: ["Caneel Bay", "Black Beauty"],
      storage: "256 GB",
      image_url: "./images/placholder.jpg",
      description:
        "A sleek, fast-charging phone with a ready-for display and a versatile camera.",
    },
    {
      id: 5,
      name: "ToughArmor 8",
      brand: "CAT",
      model: "S82",
      price: 549.95,
      currency: "USD",
      colors: ["Black", "Army Green"],
      storage: "128 GB",
      image_url: "/images/placholder.jpg",
      description:
        "Built to survive extreme conditions. Waterproof, dustproof, and drop-proof with a massive battery for extended adventures.",
    },
    {
      id: 6,
      name: "Nova Lite",
      brand: "Huawei",
      model: "Nova 12i",
      price: 299.99,
      currency: "USD",
      colors: ["Starlight Blue", "Deep Sea Black", "Peach"],
      storage: "128 GB",
      image_url: "/mini-tech/images/placholder.jpg",
      description:
        "An excellent budget-friendly option featuring a large display, impressive battery life, and a sleek design.",
    },
    {
      id: 7,
      name: "Pixel",
      brand: "Google",
      model: "Pixel 8",
      price: 699.0,
      currency: "USD",
      colors: ["Obsidian", "Hazel", "Rose"],
      storage: "128 GB",
      image_url: "/mini-tech/images/placholder.jpg",
      description:
        "The Google-powered phone with the best-in-class camera computational photography, a vibrant display, and seamless Android experience.",
    },
    {
      id: 8,
      name: "ROG Phone",
      brand: "ASUS",
      model: "8 Pro",
      price: 1299.99,
      currency: "USD",
      colors: ["Phantom Black"],
      storage: "512 GB",
      image_url: "/mini-tech/images/placholder.jpg",
      description:
        "The ultimate gaming phone. Features a super-fast refresh rate display, vapor chamber cooling, and customizable triggers for elite mobile gameplay.",
    },
  ],
};
export default phones;
