const watches = {
  category: "Smartwatches",
  products: [
    {
      id: 1,
      name: "Apple Watch",
      brand: "Apple",
      model: "Series 9",
      price: 399.0,
      currency: "USD",
      colors: ["Starlight", "Midnight", "Silver", "Product(RED)", "Pink"],
      caseSize: "41mm & 45mm",
      image_url: "/MIni-tech-store/images/placholder.jpg",
      description:
        "The most powerful Apple Watch yet. Features a bright Always-On display, advanced health sensors like ECG and blood oxygen, and crash detection.",
    },
    {
      id: 2,
      name: "Galaxy Watch",
      brand: "Samsung",
      model: "6 Classic",
      price: 369.99,
      currency: "USD",
      colors: ["Black", "Silver"],
      caseSize: "43mm & 47mm",
      image_url: "/MIni-tech-store/images/placholder.jpg",
      description:
        "A classic watch with a rotating bezel. Offers advanced health tracking, sleep coaching, and a durable sapphire crystal display. Works best with Samsung phones.",
    },
    {
      id: 3,
      name: "Versa 4",
      brand: "Fitbit",
      model: "Versa 4",
      price: 199.95,
      currency: "USD",
      colors: ["Platinum", "Black", "Waterfall Blue"],
      caseSize: "40mm",
      image_url: "/MIni-tech-store/images/placholder.jpg",
      description:
        "A fitness-focused smartwatch with built-in GPS, 40+ exercise modes, and access to Google apps. Offers a 6+ day battery life and detailed health metrics in the Fitbit app.",
    },
    {
      id: 4,
      name: "T-Rex 2",
      brand: "Amazfit",
      model: "T-Rex 2",
      price: 229.99,
      currency: "USD",
      colors: ["Black", "Green", "Sand"],
      caseSize: "47mm",
      image_url: "/MIni-tech-store/images/placholder.jpg",
      description:
        "An ultra-rugged military-grade watch built for adventure. Features dual-band GPS, 24-day battery life, and is resistant to extreme temperatures, humidity, and shock.",
    },
    {
      id: 5,
      name: "Garmin epix (Gen 2)",
      brand: "Garmin",
      model: "epix Gen 2",
      price: 899.99,
      currency: "USD",
      colors: ["Black", "White"],
      caseSize: "47mm",
      image_url: "/MIni-tech-store/images/placholder.jpg",
      description:
        "A premium multisport GPS watch with a brilliant AMOLED display. Offers mapping, advanced training metrics, health monitoring, and up to 16 days of battery life.",
    },
    {
      id: 6,
      name: "Sense 2",
      brand: "Fitbit",
      model: "Sense 2",
      price: 299.95,
      currency: "USD",
      colors: ["Platinum", "Graphite", "Blue"],
      caseSize: "40mm",
      image_url: "/MIni-tech-store/images/placholder.jpg",
      description:
        "Fitbit's most advanced health smartwatch. Includes tools for managing stress and tracking skin temperature variation (SDOV), along with ECG and heart rate tracking.",
    },
    {
      id: 7,
      name: "Pixel Watch 2",
      brand: "Google",
      model: "Pixel Watch 2",
      price: 349.99,
      currency: "USD",
      colors: ["Polished Silver", "Matte Black", "Champagne Gold"],
      caseSize: "41mm",
      image_url: "/MIni-tech-store/images/placholder.jpg",
      description:
        "The seamless Google watch. Features Fitbit health tracking, safety features like Safety Check, and deep integration with Android and Google services like Wallet and Assistant.",
    },
    {
      id: 8,
      name: "TicWatch Pro 5",
      brand: "Mobvoi",
      model: "Pro 5",
      price: 349.99,
      currency: "USD",
      colors: ["Black", "Dark Silver"],
      caseSize: "50mm",
      image_url: "/MIni-tech-store/images/placholder.jpg",
      description:
        "Runs on Wear OS with a unique dual-layer display for exceptional battery life (up to 80 days in Essential Mode). Powered by the latest Snapdragon chip for smooth performance.",
    },
  ],
};
export default watches;
